const ORIGIN='https://onceguide-devp.diave.chatgpt.site';
const $=id=>document.getElementById(id);
let state;
async function render(){state=await chrome.runtime.sendMessage({type:'STATUS'});$('status').textContent=state.recording?`${state.paused?'Paused':'Recording'} · ${state.guide?.steps.length||0} steps captured` :state.guide?`${state.guide.steps.length} steps ready to edit`:'Ready when you are.';$('start').disabled=!!state.recording;$('start').textContent=state.guide?'Start a new capture':'Start recording';$('stop').hidden=!state.recording;$('pause').hidden=!state.recording;$('pause').textContent=state.paused?'Resume recording':'Pause recording';$('open').hidden=!state.guide||state.recording;$('backup').hidden=!state.guide||state.recording;$('clear').hidden=!state.guide||state.recording;}
async function run(fn){$('error').textContent='';try{await fn();await render();}catch(e){$('error').textContent=e.message||'Something went wrong. Your existing capture is preserved.';}}
$('start').onclick=()=>run(async()=>{if(state.guide&&!confirm('Start a new capture? Download or open the current capture first. It will be replaced.'))return;const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.url||!/^https?:/.test(tab.url))throw new Error('Open a normal website tab first. Browser settings and store pages cannot be recorded.');const site=new URL(tab.url).origin;const granted=await chrome.permissions.request({origins:[site+'/*']});if(!granted)throw new Error('Site access was not granted. Nothing was recorded.');const r=await chrome.runtime.sendMessage({type:'START',tabId:tab.id,origin:site,title:tab.title});if(r.error)throw new Error(r.error);window.close();});
$('pause').onclick=()=>run(async()=>{const r=await chrome.runtime.sendMessage({type:'PAUSE'});if(r.error)throw new Error(r.error);});
$('stop').onclick=()=>run(async()=>{const r=await chrome.runtime.sendMessage({type:'STOP'});if(r.error)throw new Error(r.error);});
$('open').onclick=()=>run(async()=>{const granted=await chrome.permissions.request({origins:[ORIGIN+'/*']});if(!granted)throw new Error('Editor access was not granted. Download your capture and import it instead.');const r=await chrome.runtime.sendMessage({type:'EDITOR'});if(r.error)throw new Error(r.error);});
$('backup').onclick=()=>run(async()=>{const s=await chrome.runtime.sendMessage({type:'STATUS'});if(!s.guide)return;const url=URL.createObjectURL(new Blob([JSON.stringify(s.guide)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='once-capture.once.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);});
$('clear').onclick=()=>run(async()=>{if(confirm('Delete the capture stored by the extension? This does not delete imported guides.'))await chrome.runtime.sendMessage({type:'CLEAR'});});
chrome.storage.onChanged.addListener(()=>void render());void run(render);
