export const metadata={title:'Privacy — Once'};
export default function Privacy(){return <main style={{maxWidth:760,margin:'64px auto',padding:'0 24px',lineHeight:1.8}}>
 <a href="/">← Back to Once</a><h1>Privacy at Once</h1><p>Updated September 14, 2026. This notice describes the current beta.</p>
 <h2>Capture stays on your device</h2><p>The extension records clicks only after you start recording on an approved website. It stores step labels, the website origin, and screenshots in Chrome’s local extension storage. The editor stores imported guides in this browser’s IndexedDB. Once does not read typed field values or record keystrokes. It does not run advertising or analytics trackers.</p>
 <h2>Review screenshots before sharing</h2><p>Visible website content may contain personal or confidential information. The recorder attempts to cover form fields and marked private regions; this cannot detect every sensitive detail, closed shadow root, or visual change. Some steps are saved without a screenshot when capture cannot be completed safely. Use the editor to review, redact, or remove screenshots before exporting or sharing.</p>
 <h2>Optional hosted sharing</h2><p>Only choosing Share uploads a guide. The browser encrypts it with AES-GCM before uploading. The server stores encrypted data, an expiry time, and a hash of the deletion token. The decryption key is placed in the link fragment. Anyone with the full link and access to this deployment can read the guide. The hosting service can still observe connection metadata, and scripts running in the editor can access the unencrypted guide while it is open.</p>
 <h2>Limits and retention</h2><p>Shared links stop working after seven days or after you revoke them. Revocation deletes the hosted object. Expired objects are deleted when accessed or during bounded cleanup on later share requests; physical deletion is not guaranteed at the exact expiry time. The server uses a daily hash of the connecting IP address to limit sharing abuse, plus a global daily cap. Old rate counters are removed during subsequent share requests.</p>
 <h2>Deletion and backups</h2><p>Delete a local guide in the editor and delete the recorder capture separately in the extension. Uninstalling the extension or clearing browser storage can remove local data. Download a backup first if you want to keep it. Deleting a local guide does not revoke an existing hosted link; revoke it first. Once cannot retrieve copies downloaded or exported by other people.</p>
 <h2>Beta availability</h2><p>This deployment is currently an owner-only beta. A public support contact and publisher details must be provided before general release. There is no data sale, advertising use, or AI model training integration in this implementation.</p>
 </main>;}
