'use client';
import {useRef,useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
export function ImageEditor({image,onSave,onClose}:{image:string;onSave:(s:string)=>void;onClose:()=>void}){
 const ref=useRef<HTMLCanvasElement>(null);const [mode,setMode]=useState('redact');const [base,setBase]=useState(image);const [history,setHistory]=useState<string[]>([]);const start=useRef<{x:number;y:number}|null>(null);const [selection,setSelection]=useState<{left:string;top:string;width:string;height:string}|null>(null);
 useEffect(()=>{const img=new Image();img.onload=()=>{const c=ref.current;if(c){c.width=img.width;c.height=img.height;c.getContext('2d')!.drawImage(img,0,0);}};img.src=base;},[base]);
 function point(e:React.PointerEvent<HTMLCanvasElement>){const c=e.currentTarget;const r=c.getBoundingClientRect();return {x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
 function move(e:React.PointerEvent<HTMLCanvasElement>){const a=start.current;if(!a)return;const c=e.currentTarget;const p=point(e);const b={x:Math.max(0,Math.min(c.width,p.x)),y:Math.max(0,Math.min(c.height,p.y))};setSelection({left:Math.min(a.x,b.x)/c.width*100+'%',top:Math.min(a.y,b.y)/c.height*100+'%',width:Math.abs(a.x-b.x)/c.width*100+'%',height:Math.abs(a.y-b.y)/c.height*100+'%'});}
 function finish(e:React.PointerEvent<HTMLCanvasElement>){const a=start.current;start.current=null;setSelection(null);if(!a)return;const p=point(e);const c=e.currentTarget;const b={x:Math.max(0,Math.min(c.width,p.x)),y:Math.max(0,Math.min(c.height,p.y))};const ctx=c.getContext('2d')!;const x=Math.max(0,Math.min(a.x,b.x)),y=Math.max(0,Math.min(a.y,b.y)),w=Math.min(c.width-x,Math.abs(a.x-b.x)),h=Math.min(c.height-y,Math.abs(a.y-b.y));if(w<5||h<5)return;
  setHistory(v=>[...v,base]);if(mode==='crop'){const data=ctx.getImageData(x,y,w,h);c.width=w;c.height=h;ctx.putImageData(data,0,0);}else{ctx.fillStyle='#101916';ctx.fillRect(x,y,w,h);}setBase(c.toDataURL('image/png'));}
 return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="image-dialog"><DialogTitle>Edit screenshot</DialogTitle><DialogDescription>Drag a rectangle to crop or permanently cover sensitive information. Redaction is burned into the exported image.</DialogDescription><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="redact">Redact</TabsTrigger><TabsTrigger value="crop">Crop</TabsTrigger></TabsList></Tabs><div className="canvas-wrap"><div style={{position:'relative',display:'inline-block',lineHeight:0}}><canvas aria-label="Screenshot selection area" ref={ref} onPointerMove={move} onPointerDown={e=>{start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={finish} onPointerCancel={()=>{start.current=null;setSelection(null);}}/>{selection&&<div aria-hidden style={{position:'absolute',pointerEvents:'none',border:'2px dashed #fff',background:mode==='redact'?'#101916bb':'#14634444',...selection}}/>}</div></div><div className="row"><button className="btn" disabled={!history.length} onClick={()=>{setBase(history.at(-1)!);setHistory(h=>h.slice(0,-1));}}>Undo</button><span className="grow"/><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" onClick={()=>{if(base.length>4000000){toast.error('Image is too large. Crop it before saving.');return;}onSave(base);onClose();}}>Apply changes</button></div></DialogContent></Dialog>;
}
